### ISSUE TITLE
seperate category for block-chain related stuff

### ISSUE THREAD

**Issue by leslie-wang** [kgryte/awesome-peer-to-peer#10]
block chain is just another peer to peer technology. probably separate category can be created and link can be added as well.

**Comment by kgryte** [comment]
Yeah, thanks for the suggestion. :) TBH, my interest stemmed from WebRTC and its usage. I have not followed too closely what people are doing with blockchain related tech and certainly not to the extent that I know what repositories to include, etc. So, unless someone wants to help curate that list, I will probably have to pass on this suggestion. :(
