### ISSUE TITLE
some more libs

### ISSUE THREAD

**Issue by nickdesaulniers** [kgryte/awesome-peer-to-peer#3]
https://github.com/nickdesaulniers/node-ice
https://github.com/nickdesaulniers/node-rtc-peer-connection

**Comment by kgryte** [comment]
@nickdesaulniers Awesome! Had included `node-ice`, but somehow forgot to include `rtc-peer-connection` when I first came across it. Added you to the people section, as well. Thanks for your contributions!

**Comment by nickdesaulniers** [comment]
noice :electric_plug: :zap:
